name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python manage.py test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: th3x4v
        password: dckr_pat_pihrxgFGWYiUkV_3UHPQBfw0mkA
    - name: Build and tag the Docker image
      run: |
        IMAGE_ID=th3x4v/python_p13

        # Build the image, tag it with the commit SHA
        docker build --no-cache -t $IMAGE_ID:${GITHUB_SHA::8} . --platform=linux/amd64

        # Optionally: Push the image to a registry
        docker push $IMAGE_ID:${GITHUB_SHA::8}